INSERT INTO menu VALUES('1','Hamburguesa Bomba','Triple carne triple queso',1700);
INSERT INTO menu VALUES('2','Hamburguesa Veggie','Vegetales asados y aioli',1300);
INSERT INTO menu VALUES('3','Hamburguesa Caprichosa','Doble carne doble queso',1500);
INSERT INTO menu VALUES('4','Empanadas de carne','Carne Cortada a cuchillo',120);
INSERT INTO menu VALUES('5','Coca Cola 500cc','',500);

INSERT INTO mesa VALUES(1,'Mostrador');
INSERT INTO mesa VALUES(2,'Barra');
INSERT INTO mesa VALUES(3,'Afuera Mesa 1');
INSERT INTO mesa VALUES(4,'Afuera Mesa 2');
INSERT INTO mesa VALUES(5,'Afuera Mesa 3');


INSERT INTO estado VALUES(1,'Sin entregar');
INSERT INTO estado VALUES(2,'Pendiente a retirar');
INSERT INTO estado VALUES(3,'Retirado');
INSERT INTO estado VALUES(5,'Eliminado');

INSERT INTO clientes VALUES(1,'default@queapp.com', 'Usuario Sistema',1133221122);

INSERT INTO metodo_pago VALUES (1,'Efectivo');
INSERT INTO metodo_pago VALUES (2,'Tarjeta');
INSERT INTO metodo_pago VALUES (3,'Mercado Pago');


